/**
 * Seed data for local backend
 * Extracted so it can be shared between Convex and local storage backends
 */
export function getSeedSchemes() {
  const now = Date.now();
  const days = (d) => now + d * 24 * 60 * 60 * 1000;

  return [
    {
      name: "CGTMSE — Credit Guarantee for MSMEs",
      authority: "MSME Ministry / SIDBI",
      description: "Credit Guarantee Fund Trust for Micro and Small Enterprises provides collateral-free credit guarantees up to ₹5 crore for micro and small enterprises through member lending institutions.",
      eligibility: { sectors: ["*"], states: ["*"], maxTurnover: "5Cr-50Cr", registrationRequired: ["Udyam"] },
      benefit: "Collateral-free loans up to ₹5 crore with guarantee cover of 75–85%",
      deadline: days(180),
      applyUrl: "https://www.cgtmse.in/",
      category: "Funding",
    },
    {
      name: "PMEGP — Prime Minister's Employment Generation Programme",
      authority: "MSME Ministry / KVIC",
      description: "Credit-linked subsidy programme for setting up new micro-enterprises. Provides margin money subsidy of 15–35% of project cost.",
      eligibility: { sectors: ["*"], states: ["*"], maxTurnover: "<40L", registrationRequired: [] },
      benefit: "Margin money subsidy of 15% (urban) to 25% (rural); up to 35% for SC/ST/Women",
      deadline: days(90),
      applyUrl: "https://www.kviconline.gov.in/pmegpeportal/pmegphome/index.jsp",
      category: "Subsidy",
    },
    {
      name: "ZED Certification — Zero Defect Zero Effect",
      authority: "MSME Ministry / QCI",
      description: "National certification scheme for MSMEs to adopt quality manufacturing practices aligned with global standards.",
      eligibility: { sectors: ["Manufacturing - General", "Manufacturing - Textiles", "Manufacturing - Auto Components", "Manufacturing - Electronics"], states: ["*"], maxTurnover: null, registrationRequired: ["Udyam"] },
      benefit: "Subsidised certification (up to 80% for micro), NSIC recognition, access to government procurement portals",
      deadline: undefined,
      applyUrl: "https://zed.msme.gov.in/",
      category: "Certification",
    },
    {
      name: "CLCSS — Credit Linked Capital Subsidy Scheme",
      authority: "MSME Ministry",
      description: "Facilitates technology upgradation of MSMEs by providing 15% capital subsidy on institutional finance of up to ₹1 crore.",
      eligibility: { sectors: ["Manufacturing - General", "Manufacturing - Textiles", "Manufacturing - Auto Components", "Manufacturing - Food Processing"], states: ["*"], maxTurnover: "5Cr-50Cr", registrationRequired: ["Udyam"] },
      benefit: "Capital subsidy of 15% on institutional finance up to ₹1 crore",
      deadline: undefined,
      applyUrl: "https://msme.gov.in/credit-linked-capital-subsidy-scheme",
      category: "Subsidy",
    },
    {
      name: "SFURTI — Fund for Regeneration of Traditional Industries",
      authority: "MSME Ministry / KVIC",
      description: "Organises traditional industries and artisans into clusters to make them competitive and help them access markets.",
      eligibility: { sectors: ["Handicrafts", "Khadi", "Manufacturing - Textiles"], states: ["*"], maxTurnover: "<40L", registrationRequired: [] },
      benefit: "Cluster development funding up to ₹5 crore for heritage clusters",
      deadline: days(120),
      applyUrl: "https://sfurti.msme.gov.in/",
      category: "Funding",
    },
    {
      name: "MSME Innovative Scheme (Incubation)",
      authority: "MSME Ministry",
      description: "Supports incubation of new ideas in manufacturing, services, and agro-based industries.",
      eligibility: { sectors: ["*"], states: ["*"], maxTurnover: "<40L", registrationRequired: [] },
      benefit: "Up to ₹15 lakh grant for idea-to-prototype; up to ₹1 crore for full incubation",
      deadline: days(60),
      applyUrl: "https://msme.gov.in/msme-innovative-scheme",
      category: "Funding",
    },
    {
      name: "Udyam Registration",
      authority: "MSME Ministry",
      description: "Free online registration portal for MSMEs — the gateway to all central MSME benefits, subsidies, and priority sector lending.",
      eligibility: { sectors: ["*"], states: ["*"], maxTurnover: null, registrationRequired: [] },
      benefit: "Unlocks priority sector lending, government procurement preferences, lower interest rates",
      deadline: undefined,
      applyUrl: "https://udyamregistration.gov.in/",
      category: "Certification",
    },
    {
      name: "NSIC Raw Material Assistance",
      authority: "NSIC / MSME Ministry",
      description: "National Small Industries Corporation facilitates raw material procurement at competitive rates with deferred payment.",
      eligibility: { sectors: ["Manufacturing - General", "Manufacturing - Textiles", "Manufacturing - Auto Components", "Manufacturing - Electronics"], states: ["*"], maxTurnover: "5Cr-50Cr", registrationRequired: ["Udyam"] },
      benefit: "Financing of raw materials up to 90 days credit; access to DGS&D rate contracts",
      deadline: undefined,
      applyUrl: "https://www.nsic.co.in/",
      category: "Subsidy",
    },
    {
      name: "Section 44AD — Presumptive Tax for MSMEs",
      authority: "Ministry of Finance / CBDT",
      description: "Businesses with turnover up to ₹2 crore can declare 8% of turnover as income without maintaining full books of accounts.",
      eligibility: { sectors: ["*"], states: ["*"], maxTurnover: "40L-5Cr", registrationRequired: [] },
      benefit: "No need for full account books; presumed 8% profit rate (6% digital) reduces effective tax burden",
      deadline: undefined,
      applyUrl: "https://incometaxindia.gov.in/",
      category: "Tax Benefit",
    },
    {
      name: "GeM Portal Registration — Government e-Marketplace",
      authority: "Ministry of Commerce",
      description: "Government e-marketplace for procurement by government departments. MSMEs get price and purchase preference.",
      eligibility: { sectors: ["*"], states: ["*"], maxTurnover: null, registrationRequired: ["Udyam", "GST"] },
      benefit: "Access to ₹2+ lakh crore government procurement market; 25% purchase preference; EMD exemption",
      deadline: undefined,
      applyUrl: "https://gem.gov.in/",
      category: "Certification",
    },
    {
      name: "Telangana MSME Policy 2020 — Capital Subsidy",
      authority: "State Govt — Telangana",
      description: "Capital investment subsidy of 15–25% on fixed assets for manufacturing MSMEs in Telangana.",
      eligibility: { sectors: ["Manufacturing - General", "Manufacturing - Textiles", "Manufacturing - Electronics", "Manufacturing - Food Processing"], states: ["Telangana"], maxTurnover: "5Cr-50Cr", registrationRequired: ["Udyam"] },
      benefit: "Capital subsidy of 15–25% on fixed capital; power tariff rebate of ₹1/unit for 5 years",
      deadline: days(365),
      applyUrl: "https://industries.telangana.gov.in/",
      category: "Subsidy",
    },
    {
      name: "Maharashtra MSME Policy — Interest Subsidy",
      authority: "State Govt — Maharashtra",
      description: "Interest subsidy on term loans for manufacturing MSMEs. Rate varies by district category and enterprise size.",
      eligibility: { sectors: ["Manufacturing - General", "Manufacturing - Auto Components", "Manufacturing - Electronics"], states: ["Maharashtra"], maxTurnover: "5Cr-50Cr", registrationRequired: ["Udyam"] },
      benefit: "Interest subsidy of 5–7% on term loans for 5 years; additional benefits in Vidarbha",
      deadline: days(200),
      applyUrl: "https://www.midcindia.org/",
      category: "Subsidy",
    },
    {
      name: "Karnataka MSME Revival Package — Working Capital",
      authority: "State Govt — Karnataka",
      description: "Post-COVID revival package providing subsidised working capital loans and market access facilitation.",
      eligibility: { sectors: ["Manufacturing - General", "Technology / IT Services", "Manufacturing - Electronics"], states: ["Karnataka"], maxTurnover: "40L-5Cr", registrationRequired: ["Udyam", "GST"] },
      benefit: "Working capital loans at 4% interest; emergency credit guarantee up to ₹50 lakh",
      deadline: days(150),
      applyUrl: "https://udyogmitra.karnataka.gov.in/",
      category: "Funding",
    },
    {
      name: "UP MSME Promotional Scheme — Technology Development",
      authority: "State Govt — Uttar Pradesh",
      description: "Technology development fund for UP MSMEs — grants for technology adoption, digitisation, and process improvement.",
      eligibility: { sectors: ["Manufacturing - General", "Manufacturing - Textiles", "Handicrafts"], states: ["Uttar Pradesh"], maxTurnover: "40L-5Cr", registrationRequired: ["Udyam"] },
      benefit: "Technology adoption grant up to ₹25 lakh; additional 10% for women-owned enterprises",
      deadline: days(90),
      applyUrl: "https://niveshmitra.up.nic.in/",
      category: "Subsidy",
    },
    {
      name: "Gujarat MSME Assistance Scheme — Export Promotion",
      authority: "State Govt — Gujarat",
      description: "GIDC scheme supporting MSMEs to access export markets through trade fair subsidies and certification assistance.",
      eligibility: { sectors: ["Manufacturing - General", "Manufacturing - Textiles", "Manufacturing - Food Processing"], states: ["Gujarat"], maxTurnover: "5Cr-50Cr", registrationRequired: ["Udyam", "GST"] },
      benefit: "50% subsidy on trade fair participation; ₹5 lakh for export market development",
      deadline: days(270),
      applyUrl: "https://ic.gujarat.gov.in/",
      category: "Subsidy",
    },
    {
      name: "A-TUFS — Amended Technology Upgradation Fund (Textiles)",
      authority: "Ministry of Textiles",
      description: "Textile sector-specific scheme providing 15% capital subsidy on eligible machinery for modernisation.",
      eligibility: { sectors: ["Manufacturing - Textiles"], states: ["*"], maxTurnover: null, registrationRequired: ["Udyam"] },
      benefit: "Capital subsidy of 15% on eligible machinery; additional 10% for powerloom units",
      deadline: undefined,
      applyUrl: "https://tufs.gov.in/",
      category: "Subsidy",
    },
    {
      name: "FSSAI Registration / License for Food MSMEs",
      authority: "FSSAI / Ministry of Health",
      description: "Mandatory food safety certification for all food businesses. MSMEs with turnover under ₹12 lakh qualify for basic registration at ₹100/year.",
      eligibility: { sectors: ["Manufacturing - Food Processing", "Food & Beverages", "Agro-based Industries"], states: ["*"], maxTurnover: null, registrationRequired: [] },
      benefit: "Legal operation enabled; basic registration at ₹100/year; unlocks institutional buyer access",
      deadline: undefined,
      applyUrl: "https://foscos.fssai.gov.in/",
      category: "Certification",
    },
    {
      name: "Rajasthan MSME Assistance — Stamp Duty Exemption",
      authority: "State Govt — Rajasthan",
      description: "Stamp duty exemption on land purchase and lease for manufacturing MSMEs in Rajasthan.",
      eligibility: { sectors: ["Manufacturing - General", "Manufacturing - Textiles", "Handicrafts"], states: ["Rajasthan"], maxTurnover: "5Cr-50Cr", registrationRequired: ["Udyam"] },
      benefit: "100% stamp duty exemption on first land purchase; electricity tariff subsidy for 7 years",
      deadline: days(365),
      applyUrl: "https://industries.rajasthan.gov.in/",
      category: "Tax Benefit",
    },
  ];
}
